apiVersion: v1
kind: Namespace
metadata:
  name: arr-stack
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/homelab/arr-stack/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/homelab/arr-stack/media
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-config-pvc
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: arr-config-pv
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-data-pvc
  namespace: arr-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: arr-data-pv
  storageClassName: ''
