apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: arr-stack
spec:
  selector:
    app: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: 8191
