# Function: ARR Missing Content Manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: data
              mountPath: /data/media
              subPath: media
            - name: config
              mountPath: /config
              subPath: jellyfin
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: arr-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: arr-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jellyfin.home.lan`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
