apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /app/config
              subPath: jellyseerr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: arr-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jellyseerr.home.lan`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
