apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:develop
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: prowlarr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arr-stack
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      targetPort: 9696
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: arr-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prowlarr.home.lan`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
