apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "America/Chicago"
            - name: WEBUI_PORT
              value: "8080"
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: qbittorrent
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: arr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: arr-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  selector:
    app: qbittorrent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: arr-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`qbittorrent.home.lan`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
