kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-db-pv
  namespace: immich
  labels:
    app: immich-postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/homelab/immich-db-data
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-db-pvc
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Match or be less than the PV's capacity
  volumeName: immich-db-pv  # Bind explicitly to the PV created above
  storageClassName: ''
  