kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-library-pv
  namespace: immich
  labels:
    app: immich
spec:
  capacity:
    storage: 500Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/homelab/immich-library-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi  # Match or be less than the PV's capacity
  volumeName: immich-library-pv  # Bind explicitly to the PV created above
  storageClassName: ''
